### ISSUE TITLE
No results were returned by the query

### ISSUE THREAD

**Issue by Gatharikih** [oblac/jodd-db#3]
When I perform an operation to delete a row and then update another table I am getting the following exception.

java.lang.RuntimeException: jodd.db.DbSqlException: Query execution failed
Query: ; <--- org.postgresql.util.PSQLException: No results were returned by the query.

Caused by: org.postgresql.util.PSQLException: No results were returned by the query.
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:245)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractQueryReport$StatementProxy.invoke(AbstractQueryReport.java:215)
	at jdk.proxy2/jdk.proxy2.$Proxy68.executeQuery(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
	at jdk.proxy2/jdk.proxy2.$Proxy68.executeQuery(Unknown Source)
	at jodd.db.DbQueryBase.execute(DbQueryBase.java:690)

**Comment by igr** [comment]
This seems like something other than Jodd issue. You are probably fetching something that does not exist or so. The issue seems to be with the query.

Could you write here some code, please?
